apiVersion: core.resource-wrapper.io/v1alpha1
kind: NamespaceClass
metadata:
  name: internal-network
spec:
  networkPolicyTemplate:
    podSelector: {}
    policyTypes:
    - Ingress
    - Egress
    ingress:
    - from:
      - namespaceSelector:
          matchLabels:
            kubernetes.io/metadata.name: kube-system
    egress:
    - to:
      - namespaceSelector:
          matchLabels:
            kubernetes.io/metadata.name: kube-system
  serviceAccountTemplate:
    automountServiceAccountToken: false
